language: java

jdk:
- oraclejdk8

script: mvn install

notifications:
  email:
    recipients:
    - ksclarke@gmail.com
    on_failure: change
    on_success: never
  irc:
    channels:
    - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  slack:
    secure: eMZgS79kzSH6opY2sSJhrYdTg0jLB/JzLEvQFcn6xoDtek3/WjWWg4+M8sYv/qPqwzY3jeJ0vxd8SIwcgBJkgOHVJqvmqxWV49/F8EOENaDU+oWo5vUUh8GvM1e+B/4wZd14PbD6w9m4qs1gIAUcPECE21p0KDtvN/VYnH+96LI=

sudo: false
